### ISSUE TITLE
Discoverability in binary

### ISSUE THREAD

**Issue by tparry** [UrbanApps/UAObfuscatedString#10]
The category name shows up in the binary 
![screen shot 2015-06-17 at 8 58 40 pm](https://cloud.githubusercontent.com/assets/6304304/8205605/62d81d44-1535-11e5-936c-7f8954ec47e6.png)

Which can tip people off to look for something along the lines of: ("My password")
![screen shot 2015-06-17 at 9 05 51 pm](https://cloud.githubusercontent.com/assets/6304304/8205607/634d0abe-1535-11e5-8e45-e7a199e5464d.png)

**Comment by sferrini** [comment]
Yeah, the constant strings are stored in some place of the `__cstring` section and there is no way to get the generated string from there (because we assemble it at runtime). But we still compile the code that combines them toghether, and the selectors (which are actually called as the strings) are stored in the `__text` section. Which is simple to disassemble and as we see from the picture to understand the unobfuscated string.

**Comment by coneybeare** [comment]
"Simple" is a relative term. The average cracker is not going to be looking at assembly code. If you need stronger encryption for a stronger type of hacker, then a stronger library is probably more fitting for your app.

The only way I see around this, using the same API we currently use, would be to use some sort of cipher to generate and map the public api calls to private method names, the ones that show up in the binary. But I think thats overkill for this tiny extension.

**Comment by truemetal** [comment]
+1 @sferrini do you think it's like that in release builds as well?

**Comment by truemetal** [comment]
Ok, apparently it would; I see people suggesting to use `#define` to substitute method names to some scramble, e.g. something like this

```
#define A Y191789e 
#define B f16852da 
...etc
```

**Comment by coneybeare** [comment]
I may be wrong, but reviewing this again, when you strip debug symbols and linked products from your production build it should remove these completely.

**Comment by truemetal** [comment]
Ok, to play around with that I've created empty xcode app called `ObfuscationTestApp` and added a sample class:

```
@interface MyTestClass : NSObject
- (void) myTestMethod1;
- (void) myTestMethod2;
@end
```

After archiving for app store deployment, exporting .ipa on disk and disassembling with hopper you can clearly see this: 

<img width="361" alt="screen shot 2016-04-11 at 18 22 45" src="https://cloud.githubusercontent.com/assets/2472186/14432869/b10db562-0014-11e6-9434-36567ca66ace.png">

Function names are perfectly discoverable and the password is almost plaintext as aforementioned by @tparry 

After prepending this class with `#define`s like this the situation is improved - you can no more find any references to `MyTestClass`.

```
#define MyTestClass obj_ffxxoodd
#define myTestMethod1 sub_fbdd83
#define myTestMethod2 sub_cdeb22

@interface MyTestClass : NSObject
- (void) myTestMethod1;
- (void) myTestMethod2;
@end
```

Another interesting thing is method implementation; instead of using `@"I"` as literal string I've did the following implementation using char code:

```
- (void) myTestMethod2
{
    unichar ch = 0x0049;
    NSString *myStr = [NSString stringWithCharacters:&ch length:1];
    NSLog(@"%@", myStr);
}
```

...which translates to the following code in `hopper`. String literals visible no more!

<img width="1117" alt="screen shot 2016-04-11 at 18 35 11" src="https://cloud.githubusercontent.com/assets/2472186/14433024/43792382-0015-11e6-8095-a534cff41859.png">

I believe combining these 2 technics would significantly obfuscate discoverability of passwords in binary.

**Comment by coneybeare** [comment]
I don't think this is necessary. Did you enable "Strip Debug Symbols During Copy" and "Strip Linked Products" on your release build?

**Comment by truemetal** [comment]
I've used the default settings. I'd vote for something that works with no manual build configurations.

**Comment by coneybeare** [comment]
That didn't really answer my question. I read you comment as saying you care enough about protecting your strings to seek out a library like UAObfuscatedString, but don't care enough to properly setup your project to make that happen. Unless you can confirm that debug symbols are not stripped out using the above settings, I have to close this issue. Stripping debug symbols (the method names) from your production builds is anti-cracking 101

**Comment by sferrini** [comment]
@coneybeare "Strip Debug Symbols During Copy" will compromise your crash logs. You will no longer be able to read the stack trace, nor other useful informations.

**Comment by truemetal** [comment]
@sferrini @coneybeare agree on stack trace readability; something that concerns me as well regarding `stripping debug symbols`.

Interestingly enough with this build settings method names still perfectly discoverable by `hopper`: 

![screen shot 2016-04-12 at 13 34 02](https://cloud.githubusercontent.com/assets/2472186/14457533/cbf60ea2-00b3-11e6-9e69-1da85ab05ad9.png)

![screen shot 2016-04-12 at 13 36 32](https://cloud.githubusercontent.com/assets/2472186/14457557/f1a5a57c-00b3-11e6-950d-8b01a8c94e4e.png)

**Comment by truemetal** [comment]
Ok, another interesting thing I've just realised: the app binary is encrypted (when installed from AppStore). 
So after pulling one of my apps from iTunes backup folder on the osx, and looking at them with `otool -ov` and `class-dump` here's what I see:

![caterhamclinic_ _-bash_ _202x60_and_screenshots_and_applications](https://cloud.githubusercontent.com/assets/2472186/14458926/8d27d9da-00bd-11e6-9ebb-546a493ac58b.png)

![screen shot 2016-04-12 at 14 27 12](https://cloud.githubusercontent.com/assets/2472186/14458931/9941ec4c-00bd-11e6-9ffd-448f6678dd39.png)

Though to read plaintext password entered in source codes would require to decrypt app binary. Not as simple as using `strings` or `hopper`, that's good news. 

If we had a way to decrypt own app downloaded from App Store (maybe with provision or something) we could easily see how the binary looks there. Anybody knows a way of doing that without a jailbreak?

**Comment by coneybeare** [comment]
Keeping a copy of your DSYM is trivial, and a copy of it is even uploaded to Apple when you submit to the app store for them to be able to symbolicate your crashes. That is not a valid argument for not enabling the setting. What's unsettling is that hopper is still able to figure out some of the method names from the stripped product. Maybe hopper is smart enough to locate the DSYMs on your system? Perhaps filing a bug with the Xcode/LLVM team is the best course of action here.

**Comment by truemetal** [comment]
@coneybeare you'll have to keep `dsym`s for each build of each app you submit; and apply correct `dsym` when you get crashlogs based on app and build# (if you can symbolicate? don't know anything about that). That looks like an argument for me. 

`class-dump` is able to get names as well: 

![screen shot 2016-04-12 at 15 11 36](https://cloud.githubusercontent.com/assets/2472186/14459500/eea8c388-00c0-11e6-8607-b41b6e5a0c58.png)

The best way to see how method names look in the app binary IMO would be to decrypt and look own app downloaded from App Store; then you can know for sure what apple distributes to users' devices. 

Anybody has any ideas on this point?

**Comment by coneybeare** [comment]
It's trivial. Setup a build script to stash the DSYM on every production build. The use any number of the symbolization helpers out there to use them. Google around for symbolicate and dsym and you will find it is quite easy and effective.

**Comment by truemetal** [comment]
The more interesting question still viewing the "end-result" so to say, how the binary looks on user's iphone.

**Comment by coneybeare** [comment]
Not for me. The strip debug symbols is supposed to be doing this to prevent apps from discovering method names. If that is not working as advertised when enabled, then a bug need to be filed with Apple and the LLVM team so they can fix the tool to do what it says it is. Without doing a deeper dive, my best guess would be that hopper is locating the DSYM file to do it, or they have fully cracked that feature making it obsolete until Apple fixes.

The other possibility is that you still scanning a debug version of your app by mistake, one that includes the debug symbols.

Either way, UAOfuscatedString was never meant to be a full encryption library or bullet-proof tool. There are much stronger ways to encrypt your strings, and if your app warrants a type of protection that UAObfuscatedString can't provide, then I would suggest something like RNCryptor or rolling your own. This library was only meant to prevent the string from showing up as a whole.

**Comment by truemetal** [comment]
Ok, I've laid out things that was on my mind for this topic here: https://github.com/truemetal/iOS-apps-security-notes 
Anybody who'd like to proceed the investigation / discussion is welcome on that repo! 

Thanks

**Comment by AnthonyMDev** [comment]
So just to clarify, no changes have been made to this library to address the vulnerability that was found by @tparry right?

**Comment by coneybeare** [comment]
No, @tparrys issues were caused by not enabling the standard "Strip Debug Symbols During Copy" and "Strip Linked Products" compiler flags on release products. When used properly, all symbols are obfuscated as intended by UAObfuscatedString.
