### ISSUE TITLE
Can I use this with SWIFT?

### ISSUE THREAD

**Issue by Foddy** [UrbanApps/UAObfuscatedString#15]
I tried to add this lib into my swift project via the bridging header but I don't know how to use it to create a string. 

Using the syntax as described like this _"Obfuscate.T.h.i.s..i.s..a..t.e.s.t.dot"_ does not work?

Many thanks!

**Comment by nchodelski** [comment]
Hey guys, check out this solution someone posted in another issue thread  - Obfuscate has been re-written in Swift [here](https://gist.github.com/Jiropole/a02309b83492151834c7432b37dad7e9).

**Comment by pjebs** [comment]
Hey @nchodelski. Did you know we've actually met.
I always check out everyone who stars my repos and knew we had met a few years back.

**Comment by nchodelski** [comment]
Hey there, thanks for the awesome ios tools you've built!  I'm  still figuring out if i can use Obfuscate in my in app purchase code (app is entirely swift atm) but it looks really useful. :)

Did we meet somewhere in Australia?  I used to live in Melbourne.

**Comment by pjebs** [comment]
Yes in Melb. Long story though.
Of course you can use the obfuscator for ANY strings.
The most important thing about in app purchase is to do receipt validation. Most people don't do that.

**Comment by nchodelski** [comment]
I'm doing receipt validation but I dont have access to a 3rd party server so I'm trying to check a variety of hardcoded & obfuscated strings in addition to validating with Apple, to add more security to the validation process.

**Comment by pjebs** [comment]
You don't need 3rd party server (although it is recommended). You can get app to do that in the same way the server does it.

**Comment by pjebs** [comment]
You do know you can now use swift for server programming? $5 digital ocean server (if you are just doing receipt validation it may be enough).
Some good frameworks are perfect.org or vapour

**Comment by nchodelski** [comment]
I did look at local/ app side validation with some cocoapods and Open SSL
but the scale to set up was beyond the budget for my project.  Making my
own server is a good idea though. I have heard a bit about Perfect...might
try setting it up on a Linux box at home... it would be a good way to learn
about server side swift.

**Comment by pjebs** [comment]
When did you start doing apps. When I met you you were focussing on ants

**Comment by pjebs** [comment]
App side validation with cocoapods + openssl + beyond budget.  I think you were doing it wrong

**Comment by pjebs** [comment]
Those keywords suggest that

**Comment by RomanPodymov** [comment]
Hello @Foddy 
Yes, you can use this library with Swift. Please close the issue.

**Comment by Foddy** [comment]
Oh! In the meantime all my "secret" keys have been leaked across the internet... 😅

(kidding, just in case a client jumps into that issue)
