### ISSUE TITLE
Error: '$' is not an identifier; use backticks to escape it

### ISSUE THREAD

**Issue by rsaenzi** [UrbanApps/UAObfuscatedString#28]
When I install the project on a new Xcode Project and compile it, Xcode shows this error:
UAObfuscatedString.swift:101:9: '$' is not an identifier; use backticks to escape it

<img width="781" alt="error" src="https://user-images.githubusercontent.com/2594928/34266112-185606ca-e646-11e7-98b6-72de216719bb.png">

**Comment by thattyson** [comment]
Looks like this is fixed in master but the cocoapod hasn't been updated

**Comment by mrianmerry** [comment]
I emailed @coneybeare directly to address this, so hopefully the cocoapod will be updated soon!
