### ISSUE TITLE
Capital i "I" method conflicts with macro "I" defined in 10.11 SDK

### ISSUE THREAD

**Issue by gregcotten** [UrbanApps/UAObfuscatedString#9]

**Comment by coneybeare** [comment]
Its too early in the beta to be making changes just yet. If it stays conflicted, we will change before the GM

**Comment by gregcotten** [comment]
I agree. Not sure if the issue should be closed, though.

**Comment by Ewg777** [comment]
@coneybeare any work around?

**Comment by coneybeare** [comment]
I haven't checked it out yet, but would entertain any pull request that has a good fix.

**Comment by Ewg777** [comment]
@coneybeare #4

**Comment by coneybeare** [comment]
Nope, out of sync with current code and reduced readability of the code.

**Comment by gregcotten** [comment]
I don't think there is a workaround that allows you to keep "I" intact. It will have to become less readable.

**Comment by coneybeare** [comment]
Perhaps, but we could underscore, or another workaround for, only the "I" instead of the entire set.

**Comment by truemetal** [comment]
@coneybeare yeah, why not just have underscore added? 
Since there's no official fix, I'm having a copy of `UAObfuscatedString` with this one change. Works fine for months already :) 

 `- (instancetype)_I;`

**Comment by coneybeare** [comment]
Yes, I would approve that pull request.

**Comment by truemetal** [comment]
@coneybeare https://github.com/UrbanApps/UAObfuscatedString/pull/17

**Comment by gregcotten** [comment]
This is def closed
